modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="safegecko"
version="1.0"
displayName="SafeGecko"
description='''
SafeGecko Mod
'''

[[dependencies.safegecko]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.safegecko]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"